---
os: linux
dist: bionic
language: go
go:
- 1.17.5
services:
- docker
go_import_path: github.com/coreos/etcd-operator
install:
- ./hack/update_vendor.sh
cache:
  directories:
  - vendor
  - $GOPATH/pkg/mod
  - $HOME/.cache/go-build
script:
- ./hack/build/operator/build
- ./hack/build/backup-operator/build
- ./hack/build/restore-operator/build
deploy:
- provider: script
  script: bash ./hack/deploy.sh
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
