---
os: linux
dist: bionic
language: go
go:
- 1.11.5
services:
- docker
env:
- GO111MODULE=off
go_import_path: github.com/coreos/etcd-operator
before_install: go get -u github.com/golang/dep/cmd/dep
install:
- ./hack/update_vendor.sh
cache:
  directories:
  - vendor
script:
- ./hack/build/operator/build
- ./hack/build/backup-operator/build
- ./hack/build/restore-operator/build
deploy:
- provider: script
  script: bash ./hack/deploy.sh
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
